### ISSUE TITLE
Add bluetooth address to the title (as in the app)

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/ruuvitag-adapter#11]
When a RuuviTag is recognised and added into the gateway, it is put in with a default name of RuuviTag. I bought a 3 pack of RuuviTags so it is hard to tell which is which in the gateway.
I would like to suggest that the default name includes the last 4 characters of the Bluetooth id. This is the approach that Ruuvi have taken in their IOS app, which makes it easier to give them more meaningful names.

**Comment by chas-iot** [comment]
I'll see if I can do this and submit a PR in the next few days

**Comment by tim-hellhake** [comment]
Good idea!

**Comment by tim-hellhake** [comment]
Did you have a chance to test it?
The new update should have fixed it.

**Comment by chas-iot** [comment]
I've been working on all the other stuff so did not really look at this (see my pull request :) ). I see what you did as I am working with the code

**Comment by tim-hellhake** [comment]
I just wondered if there was anything left because the issue was still open 😄.
