### ISSUE TITLE
How to filter out invalid values?

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/ruuvitag-adapter#14]
A graph in the Gateway Logs just showed me this
![image](https://user-images.githubusercontent.com/65324897/84645704-92d75580-af33-11ea-86ea-2c969097dbb7.png)
I checked the specification and 164% comes from the invalid value 65535

What is your preferred approach to filter these out? 

What I suggest an approach like the following
In ruuvitag-parser.ts
````javascript
let reading = null;
if (payload.readUInt16BE(location) != 65535) {
    reading = payload.readUInt16BE(location);
}
````
In ruuvitag-adapter.ts
````javascript
if (reading != null) {
    this.property.setCachedValueAndNotify(reading);
}
````
If this is OK as an approach then I will create a new PR

**Comment by tim-hellhake** [comment]
> What is your preferred approach to filter these out?

I would not send them in the first place.

> If this is OK as an approach then I will create a new PR

Looks good to me.
