### ISSUE TITLE
HomeKit adapter incompatibility

### ISSUE THREAD

**Issue by jmdouglas** [tim-hellhake/ruuvitag-adapter#29]
Hi,
Is this plugin compatible with [WebThingsIO/homekit-adapter](https://github.com/WebThingsIO/homekit-adapter)? Starting the RuuviTag adapter causes Bluetooth devices connected through HomeKit adapter to become disconnected. I don't have any wifi devices connected, so I don't know if they would also stop working.
I'm running WebThings on an RPi4. I tried setting the broadcast to every 6 seconds (RAWv2-slow) in case the tag was causing congestion, but that doesn't seem to solve it.
Thanks for your help.

**Comment by tim-hellhake** [comment]
Hi @jmdouglas,

Unfortunately, that is a [known problem](https://github.com/WebThingsIO/gateway/issues/1437).
Using noble in multiple addons can cause weird issues.
The only solution I have so far is using another PI or a cheap external MCU like the ESP32 as BLE Gateway.
Please let me know if this would be a solution for you.

**Comment by jmdouglas** [comment]
Ah, I'll figure something out. Thanks for the reply!
