### ISSUE TITLE
cannot 'discover' RuuviTags

### ISSUE THREAD

**Issue by chas-iot** [tim-hellhake/ruuvitag-adapter#9]
This issue has two parts.

The first part is that the adaptor does not get the event that triggers the log lines `Noble adapter is poweredOn` and `Start scanning for devices` until I login to my Raspberry Pi, start `bluetoothctl` and type a command like `discoverable on` or `scan on`. I tried reboots of the Raspberry Pi and restarts of the mozilla-iot-gateway.service - neither trigger this initial event.

Part two is that even after that trigger, it never discovers the RuuviTags. I added a line in the compiled addon js: `console.log(JSON.stringify(peripheral));` to capture any discovered device, and it did not log anything.

The RuuviTags do show up in `bluetoothctl` on the Raspberry Pi and also show up in the app on my phone.

**Comment by chas-iot** [comment]
I looked at the code and it appears that this is more of an https://github.com/abandonware/noble issue.
What is possibly relevant is that I have a fully up-to-date Raspbian on RPi 4.

**Comment by tim-hellhake** [comment]
Hi @chas-iot,
sorry for the late reply.
I wanted to make sure I can reproduce the error here first.
I flashed the latest gateway image to a new sd card and ran it on a raspberry pi 4.

![image](https://user-images.githubusercontent.com/17127122/84081723-cb7ca980-a9de-11ea-9b79-93f13cbe25b7.png)

As you can see bluetooth was enabled right away, and my ruuvitag was detected successfully.

> What is possibly relevant is that I have a fully up-to-date Raspbian on RPi 4.

Do you use a vanilla raspbian image or the raspbian based gateway image?

**Comment by chas-iot** [comment]
> Do you use a vanilla raspbian image or the raspbian based gateway image?

I originally used the raspbian based gateway image and then used apt to update it.

**Comment by chas-iot** [comment]
> I originally used the raspbian based gateway image and then used apt to update it.

I did this because, for my own enjoyment rather than a specific technical requirement, I expose the gateway on the internet via a self hosted nginx reverse proxy so I want to ensure the gateway is fully patched. Additionally, I scrapped the micro-sd card and host the RPi storage on TFTP and NFS.

**Comment by chas-iot** [comment]
I found the issue. Because I'm running on NFS, the node executable lost the Linux capability required to access the Bluetooth adaptor.

**Comment by tim-hellhake** [comment]
Good to know.
Thanks for the info!
